version: '3'
services:
  dbm:
    image: postgres:12
    container_name: sql-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis-db
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - dbm
      - redis
    env_file:
      - .env-docker

volumes:
  pgdata:
